migration_laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/pertanyaan', 'PertanyaanController@index');
// Route::get('/pertanyaan/create', 'PertanyaanController@create');
// Route::post('/pertanyaan', 'PertanyaanController@store');
// Route::get('/pertanyaan/{pertanyaan_id}', 'PertanyaanController@show');
// Route::get('/pertanyaan/{pertanyaan_id}/edit', 'PertanyaanController@edit');
// Route::put('/pertanyaan/{pertanyaan_id}', 'PertanyaanController@update');
// Route::delete('/pertanyaan/{pertanyaan_id}', 'PertanyaanController@destroy');

Route::resource('pertanyaan', 'PertanyaanController');
Route::post('/pertanyaan/{pertanyaan}', 'PertanyaanController@like')->name('pertanyaan.like');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
  \UniSharp\LaravelFilemanager\Lfm::routes();
});

migration_laravel/app/LikeDislikePertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LikeDislikePertanyaan extends Model
{
    protected $table = 'like_dislike_pertanyaan';
    protected $guarded = [];
}

migration_laravel/app/Pertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pertanyaan extends Model
{
    protected $table = "pertanyaan";
    protected $fillable = ['judul', 'isi', 'tanggal_dibuat', 'tanggal_diperbaharui', 'profil_id'];
    protected $guarded = [];

    public function author(){
        return $this->belongsTo('App\User', 'profil_id');
    }

    public function likeDislike(){
        return $this->belongsToMany('App\User', 'like_dislike_pertanyaan', 'pertanyaan_id', 'profil_id')
            ->withPivot('poin')
            ->withTimestamps();
    }
}

migration_laravel/app/Profil.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profil extends Model
{
    protected $table = "profil";

    public function user(){
        return $this->belongsTo('App\User', 'user_id');
    }
}

migration_laravel/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profil(){
        return $this->hasOne('App\Profil', 'user_id');
    }

    public function pertanyaan(){
        return $this->hasMany('App\Pertanyaan', 'profil_id');
    }

    public function likeDislike(){
        return $this->belongsToMany('App\Pertanyaan', 'like_dislike_pertanyaan', 'profil_id', 'pertanyaan_id')
            ->withPivot('poin')
            ->withTimestamps();
    }
}

migration_laravel/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

migration_laravel/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('pertanyaan');
    }
}

migration_laravel/app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use App\LikeDislikePertanyaan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use App\Pertanyaan;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;

class PertanyaanController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); // ->except(['index']);
    }

    public function index()
    {
        // $items = DB::table('pertanyaan')->get();

        $items = Pertanyaan::all();

        // $user = Auth::user();
        // $items = $user->pertanyaan;
        return view('pertanyaan.index', compact('items'));
    }

    public function create()
    {
        return view('pertanyaan.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'judul' => 'required|max:255',
            'isi' => 'required'
        ]);

        $currentTime = Carbon::now()->toDateTimeString();

        // $query = DB::table('pertanyaan')->insert([
        //     'judul' => $request['judul'],
        //     'isi' => $request['isi'],
        //     'tanggal_dibuat' => $currentTime,
        //     'tanggal_diperbaharui' => $currentTime
        // ]);

        // $pertanyaan = new Pertanyaan;
        // $pertanyaan->judul = $request['judul'];
        // $pertanyaan->isi = $request['isi'];
        // $pertanyaan->tanggal_dibuat = $currentTime;
        // $pertanyaan->tanggal_diperbaharui = $currentTime;
        // $pertanyaan->save();

        // $pertanyaan = Pertanyaan::create([
        //     'judul' => $request['judul'],
        //     'isi' => $request['isi'],
        //     'tanggal_dibuat' => $currentTime,
        //     'tanggal_diperbaharui' => $currentTime,
        //     'profil_id' => Auth::user()->id
        // ]);

        $user = Auth::user();

        $pertanyaan = $user->pertanyaan()->create([
            'judul' => $request['judul'],
            'isi' => $request['isi'],
            'tanggal_dibuat' => $currentTime,
            'tanggal_diperbaharui' => $currentTime,
        ]);

        Alert::success('Berhasil', 'Berhasil Main');
        return redirect('/pertanyaan')->with('success', 'Pertanyaan telah ditambahkan');
    }

    public function show($id)
    {
        // $item = DB::table('pertanyaan')->where('id', $id)->first();
        $item = Pertanyaan::find($id);
        $like = 0;
        if (LikeDislikePertanyaan::where([['pertanyaan_id', $id], ['profil_id', Auth::user()->id]])->first()){
            $like = 1;
        }
        return view('pertanyaan.detail', compact('item'))->with('like', $like);
    }

    public function edit($id)
    {
        // $item = DB::table('pertanyaan')->where('id', $id)->first();
        $item = Pertanyaan::find($id);

        return view('pertanyaan.edit', compact('item'));
    }

    public function update($id, Request $request)
    {
        $request->validate([
            'judul' => 'required|max:255',
            'isi' => 'required'
        ]);

        $currentTime = Carbon::now()->toDateTimeString();

        // $query = DB::table('pertanyaan')
        //     ->where('id', $id)
        //     ->update([
        //         'judul' => $request['judul'],
        //         'isi' => $request['isi'],
        //         'tanggal_diperbaharui' => $currentTime
        //     ]);

        $pertanyaan = Pertanyaan::where('id', $id)
            ->update([
                'judul' => $request['judul'],
                'isi' => $request['isi'],
                'tanggal_diperbaharui' => $currentTime
            ]);

        return redirect('/pertanyaan')->with('success', 'Pertanyaan telah diperbaharui');
    }

    public function destroy($id)
    {
        // $query = DB::table('pertanyaan')->where('id', $id)->delete();
        Pertanyaan::destroy($id);

        return redirect('/pertanyaan')->with('success', 'Pertanyaan telah dihapus');
    }

    public function like($id)
    {
        $user = Auth::user();
        
        if (LikeDislikePertanyaan::where([['pertanyaan_id', $id], ['profil_id', Auth::user()->id]])->first()){
            LikeDislikePertanyaan::where([['pertanyaan_id', $id], ['profil_id', Auth::user()->id]])->delete();
        } else {
            $user->likeDislike()->attach([$id => ['poin' => 1]]);
        }

        return redirect("/pertanyaan");
    }
}

migration_laravel/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

migration_laravel/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

migration_laravel/resources/views/pertanyaan/create.blade.php
@extends('template.master')

@push('scripts-head')
  <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@endpush

@section('content')
<div class="card">
  <div class="card-header bg-primary">
    <h3 class="card-title text-white">Buat Pertanyaan</h3>
  </div>
  <div class="card-body p-0">
    <form action="/pertanyaan" method="POST">
      @csrf
      <div class="p-4">
        <div class="form-group">
          <label for="judul">Judul Pertanyaan</label>
          <input type="text" class="form-control" id="judul" name="judul" value="{{ old('judul', '') }}" placeholder="Masukkan Judul">
          @error('judul')
              <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="isi">Isi Pertanyaan</label>
          {{-- <textarea class="form-control" id="isi" name="isi" rows="3">{{ old('isi', '') }}</textarea> --}}
          <textarea name="isi" class="form-control my-editor">{!! old('isi', '') !!}</textarea>
          @error('isi')
              <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
      </div>
      <div class="card-footer text-muted">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
</div>
@endsection

@push('scripts')
<script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endpush

migration_laravel/resources/views/pertanyaan/detail.blade.php
@extends('template.master')

@section('content')
<div class="card p-4">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="mb-4 text-center">
        <h1 class="mb-4">{{ $item->judul }}</h1>
      </div>
    </div>
    <div class="col-3 d-flex justify-content-end">
      <form action="{{ route('pertanyaan.like', ['pertanyaan' => $item->id]) }}" method="POST">
        @csrf
        @if ($like == 1)
          <input type="submit" class="btn btn-primary" name='like' value="Like">
        @else
          <input type="submit" class="btn btn-outline-primary" name='like' value="Like">
        @endif
      </form>
    </div>
  </div>
  <p>{!! $item->isi !!}</p>
  <div class="text-muted mt-4">
    <small>Author     : {{ $item->author->name }}</small>
    <br>
    <small>Updated at : {{ $item->tanggal_diperbaharui }}</small>
    <br>
    <small>Created at : {{ $item->tanggal_dibuat }}</small>
  </div>
</div>
@endsection

migration_laravel/resources/views/pertanyaan/edit.blade.php
@extends('template.master')

@section('content')
<div class="card">
  <div class="card-header bg-primary">
    <h3 class="card-title text-white">Edit Pertanyaan</h3>
  </div>
  <div class="card-body p-0">
    <form action="/pertanyaan/{{ $item->id }}" method="POST">
      @csrf
      @method('PUT')
      <div class="p-4">
        <div class="form-group">
          <label for="judul">Judul Pertanyaan</label>
          <input type="text" class="form-control" id="judul" name="judul" value="{{ old('judul', $item->judul) }}" placeholder="Masukkan Judul">
          @error('judul')
              <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="isi">Isi Pertanyaan</label>
          <textarea class="form-control" id="isi" name="isi" rows="3">{{ old('isi', $item->isi) }}</textarea>
          @error('isi')
              <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
      </div>
      <div class="card-footer text-muted">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
</div>
@endsection

migration_laravel/resources/views/pertanyaan/index.blade.php
@extends('template.master')

@section('content')
  <div class="card p-4">
    <div class="row">
      <div class="col-3"></div>
      <div class="col-6">
        <div class="mb-4 text-center">
          <h1 class="mb-4">Daftar Pertanyaan</h1>
          @if (session('success'))
            <div class="alert alert-success">
              {{ session('success') }}
            </div>
          @endif
          <a href="{{ route('pertanyaan.create') }}" class="btn btn-primary">Tambah Pertanyaan</a>
        </div>
      </div>
      <div class="col-3">
        @guest
          <div class="d-flex justify-content-end">
            <a class="btn btn-secondary mr-2" href="/login">Login</a>
            <a class="btn btn-outline-secondary" href="/register">Register</a>
          </div>
        @else
          <div class="d-flex justify-content-end">
            <a id="navbarDropdown" class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
              Halo, {{ Auth::user()->name }} <span class="caret"></span>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ route('logout') }}"
                  onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                  {{ __('Logout') }}
              </a>

              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
              </form>
            </div>
          </div>
        @endguest
      </div>
    </div>
    <div class="row">
      @forelse ($items as $key => $item)
        <div class="col-sm-6 mb-4">
          <div class="card text-center">
            <div class="card-header">
              <h5 class="card-title">{{ $item->judul }}</h5>
            </div>
            <div class="card-body">
              <p class="card-text">{!! $item->isi !!}</p> 
            </div>
            <div class="card-footer text-muted" style="justify-content: center; display:flex;">
              <a href="{{ route('pertanyaan.show', ['pertanyaan' => $item->id]) }}" class="btn btn-info mr-2">Show</a>
              <a href="/pertanyaan/{{ $item->id }}/edit" class="btn btn-warning mr-2">Edit</a>
              <form action="/pertanyaan/{{ $item->id }}" method="POST">
                @csrf
                @method('DELETE')
                <input type="submit" value="delete" class="btn btn-danger">
              </form>
            </div>
          </div>
        </div>
      @empty
        <div class="col-12 text-center">
          <p>tidak ada pertanyaan</p>
        </div>
      @endforelse
    </div>
  </div>
@endsection

migration_laravel/resources/views/template/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Aplikasi Web Forum</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  @stack('scripts-head')
</head>
<body>
  <div class="container my-5">
    @yield('content')
  </div>
</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
@include('sweetalert::alert')
@stack('scripts')
</html>